name: Build the software automatically

on: [issues]
permissions:
  issues: write
  contents: read
jobs:
  start:
    env:
      PASSWORD: ${{vars.PASSWORD}}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: startsWith(github.event.issue.title, '[build]')
    steps:
    - uses: actions/checkout@v3
    - name: Checking the issue template
      if: contains(github.event.issue.body, '"') == false
      run: echo Issue body is "${{github.event.issue.body}}"
    - name: Building the code
      run: |
        echo "Running build script with ${{secrets.FLAG1}}"
        chmod +x build.sh
        ./build.sh ${{secrets.FLAG1}}
