name: Build the software

on: [issues]
permissions:
  issues: write
  contents: read
jobs:
  start:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checking the issue template
      if: startsWith(github.event.issue.title, '[build]')
      run: echo Issue body is "${{github.event.issue.body}}"
    - uses: actions/checkout@v3
    - name: Building the code
      run: |
        echo "Running build script with ${{secrets.FLAG1}}"
        ls
        pwd
        ./build.sh ${{secrets.FLAG1}}
